[development]
address = "localhost"
port = 8000
redis = "redis://localhost4/"

[development.databases]
events = { url = "postgres://events:events@localhost4/events" }

[production]
address = "0.0.0.0"
port = 8000
redis = "redis://redis/"

[production.databases]
events = { url = "postgres://events:events@db/events" }
