version: '3.7'

services:
  app:
    ports:
      - 5660:5660

  db:
    image: postgres:11.5
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: events
      POSTGRES_USER: events
    networks:
      adminer:
        aliases: [events]
      default:
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data:rw

networks:
  adminer:
    external: true

volumes:
  db:
